services:
  postgres:
    image: postgres:16-alpine
    container_name: ikstore-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ikstore
      POSTGRES_PASSWORD: ikstore
      POSTGRES_DB: ikstore
    ports:
      - "5432:5432"
    volumes:
      - ikstore_pg_data:/var/lib/postgresql/data

volumes:
  ikstore_pg_data:
